name: good_living_launcher
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_remix: ^0.0.3
  device_apps: ^2.2.0
  easy_pie_chart: ^1.0.0
  path_provider: ^2.1.2
  pie_chart: ^5.4.0
  flex_color_picker: ^3.3.1
  scrollable_positioned_list: ^0.3.8
  objectbox: ^2.4.0
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  get_it: ^7.6.7
  meta: ^1.10.0
  bloc: ^8.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
